spring.application.name=fundfast
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/fundfast_db?ifnotexists=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mohan
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8080
